[package]
name = "cringe_bot"
version = "0.1.0"
authors = ["Timmy Xiao <timmyxiao1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"
regex = "0.2"
lazy_static = "1.4.0"
